#
# Shared
#
key_name: 20161025-dataops-{{ env }}
state: present
bucket: telemetry-presto-emr

#
# Presto
#
presto_stack_name: telemetry-presto
presto_coordinator_type: m4.xlarge
presto_worker_count: 32
presto_worker_type: m4.xlarge
presto_query_max_memory: 96GB
presto_query_node_memory: 6GB
presto_emr_release: emr-5.1.0

#
# Metastore
#
metastore_stack_name: telemetry-metastore
metastore_master_type: m4.large
metastore_core_type: m4.large
metastore_core_count: 2
metastore_emr_release: emr-5.0.0
