- name: provision aws resources
  hosts: localhost
  remote_user: ubuntu
  vars:
    - region: us-west-2
    - bucket: telemetry-presto-emr

  tasks:
    - name: create bucket
      s3: bucket={{bucket}} region={{region}} mode=create

    - name: copy EMR bootstrap script
      s3: bucket={{bucket}} region={{region}} object=bootstrap/telemetry.sh src=files/telemetry.sh mode=put

    - name: copy EMR configuration
      s3: bucket={{bucket}} region={{region}} object=configuration/configuration.json src=files/configuration.json mode=put

